spring.application.name=leave-portal-app
spring.config.import=optional:file:.env[.properties]
# OCI Configuration
oci.region=us-ashburn-1
oci.namespace=idqag2xakgns
oci.bucket-name=sick-leaves-bucket
oci.config-file=~/.oci/config
oci.profile=DEFAULT

# OAuth Configuration (Google)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Database
spring.datasource.url=jdbc:oracle:thin:@//129.213.126.140:1529/FREEPDB1
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080
server.address=0.0.0.0
server.forward-headers-strategy=framework