spring.application.name=leave-portal-app
spring.config.import=optional:file:.env[.properties]
# OCI Configuration
oci.region=us-ashburn-1
oci.namespace=idqag2xakgns
oci.bucket-name=sick-leaves-bucket
oci.config-file=C:/Users/Codeline/.oci/config
oci.profile=DEFAULT

# OAuth Configuration (Google)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Server
server.port=8080